### ISSUE TITLE
Many issues with the old BetterNether mod (Which affect this fork).

### ISSUE THREAD

**Issue by MagmaSlime123** [Rebirth-of-the-Night/BetterNether#1]
Not really much to say via the title. Both the old mod and this fork have quite a few issues, such as biomes sorta.. Mixing/bleeding into each other, and a few other QoL issues.

Other mods are being used, however all of this can be replicated with just BetterNether (Or this fork), Biomes o' Plenty, and NetherEx.

Undergarden biome with bits of BetterNether tiny mushrooms mixed in.
![2021-05-21_11 20 51](https://user-images.githubusercontent.com/51277766/119175038-32dc0f80-ba1e-11eb-9d39-7036c59bc55e.png)

Corrupted Sands mixing with Gravel Deserts.
![2021-05-21_12 29 51](https://user-images.githubusercontent.com/51277766/119182486-d2ea6680-ba27-11eb-8cd3-8251958ad451.png)

BetterNether biomes also have no biome name in the F3 menu.
![2021-05-21_11 23 57](https://user-images.githubusercontent.com/51277766/119175341-8c443e80-ba1e-11eb-8ccc-6cc762eba0e4.png)

Ruthless Sands mixed with a Bone Reef.
![2021-05-21_13 02 38](https://user-images.githubusercontent.com/51277766/119186156-8a817780-ba2c-11eb-9ae3-1906194646d3.png)

Suggestions or QoL Issues:

Gravel Deserts, due to them being, well, gravel deserts, also have a TON of floating gravel. This can possibly cause a LOT of FPS/TPS issues if said blocks get block updates (Which you'll see a LOT of while flying through a few). May not be possible since gravel might be hard to deal with, though I have no idea.

Most of BetterNether's bone blocks are also unneeded since the Bone Reef biome now uses vanilla's bone blocks (Not sure if this was changed but if it was, then hurray, lol).

Since Biomes o' Plenty adds its own netherrack mycelium, a config option should be added to allow the fungi forest/mushroom forest to use BoP's netherrack or BetterNether's netherrack mycelium (Or whatever it should've been called since again, no name is specified in the F3 debug) to prevent 2 types of nether mycelium from being created, though BetterNether's tiny mushrooms would need to be changed to have compat. with BoP''s mycelium.

Disabling the Wart Seed block will prevent the big wart trees from appearing in the Wart Forest biome.
Disabling Small or Large Eyeball blocks will prevent Stalagnate from generating.
Combine the Small, Large Eyeball, and the Eye Vine blocks into 1 config option.

Eyeball blocks give off drip particles, but said particles do nothing. Add an option to allow eyeball blocks, like rain, to slowly fill cauldrons under them.

Small Mushrooms don't auto-break themselves, like how tallgrass or like how cutting a tree down in real life works. In 1.16, this was added to most plant blocks that are multiple blocks tall, like the mushrooms.
![2021-05-21_13 11 25](https://user-images.githubusercontent.com/51277766/119186996-8f92f680-ba2d-11eb-922e-cd920f314f15.png)

Lucis Spores having wrong rotation states when generated.
![2021-06-26_22 06 25](https://user-images.githubusercontent.com/51277766/123532490-53a12000-d6c2-11eb-9785-033325323b4f.png)

**Comment by TwilightFlower** [comment]
All of these are working as intended, and are feature/change requests rather than a bug report. BetterNether biomes are not actual biomes, hence them not appearing on the F3 menu, but a sort of... space... overlay... thing. There seem to be a few actual bugs mixed in here, but those should each be submitted as their own issue report.

**Comment by MagmaSlime123** [comment]
Why do other biome mods have actual biomes then. Why doesn't this reflect that.

Ive put these issues as their own reports instead.

Sorry if I shouldn't. For some reason.

**Comment by democat3457** [comment]
They aren’t biomes because iirc they also take up finite vertical space

**Comment by MagmaSlime123** [comment]
Uhhh.... I'm confused.

**Comment by Foreck1** [comment]
That means that they are biome "clusters" similar to Quark's cave biomes, which in turn, allows for more of these isolated "biomes" to be on top of each other and not occupy the whole chunk.

**Comment by MagmaSlime123** [comment]
Oh.
