### ISSUE TITLE
Crash.

### ISSUE THREAD

**Issue by MagmaSlime123** [Rebirth-of-the-Night/BetterNether#14]
See the report. Modlist in it.

https://pastebin.com/pHF1vZC5

Apparently some structure is wanting to generate and can't.

**Comment by democat3457** [comment]
is the cincinnasite fire bowl disabled

**Comment by MagmaSlime123** [comment]
Yes.

**Comment by democat3457** [comment]
Should be fixed now in https://www.curseforge.com/minecraft/mc-mods/betternether-rotn-edition/files/3642873 (along with #8)

**Comment by MagmaSlime123** [comment]
Ah, alright. Thanks.
