### ISSUE TITLE
Why is Albedo an optional dependency?

### ISSUE THREAD

**Issue by MagmaSlime123** [Rebirth-of-the-Night/BetterNether#16]
Title.

None of this mod's blocks have colored lighting when the mod is installed. So, kinda confused as to why its an optional dependency that doesn't function at all. Albedo also has 0 support for modded blocks and Vanilla's as well. And all addons for said mod are dead and have many crash issues. I'd recommend either removing support or forking and fixing its many issues, since the dev won't apparently.

**Comment by democat3457** [comment]
The only thing it’s used for is special lighting on the firefly entity

**Comment by democat3457** [comment]
https://github.com/Rebirth-of-the-Night/BetterNether/blob/mc_1.12.2/src/main/java/paulevs/betternether/entities/EntityFirefly.java

**Comment by MagmaSlime123** [comment]
Huh. This wasn't mentioned anywhere in any changelog.

Sorry for sounding rude, btw. Albedo and its addons are all dead, stuck in a WIP state and have crash issues. So was a bit concerned about why you were using it.

**Comment by democat3457** [comment]
This thing has been around since April 2021 apparently

**Comment by democat3457** [comment]
> Sorry for sounding rude, btw. Albedo and its addons are all dead, stuck in a WIP state and have crash issues. So was a bit concerned about why you were using it.

That's fair tbh; we don't even use it in RotN, but the restored optional functionality is there for anyone who wants it

**Comment by MagmaSlime123** [comment]
Ah, alright. Was just wondering.
