### ISSUE TITLE
In 1.16x, BetterNether's plants don't float if broken from the bottom, like chorus fruit. Please fix this for 1.12.

### ISSUE THREAD

**Issue by MagmaSlime123** [Rebirth-of-the-Night/BetterNether#5]
Title.

![image](https://user-images.githubusercontent.com/51277766/124838050-e64f8380-df3a-11eb-8231-cc23d47dceb9.png)

**Comment by democat3457** [comment]
Not a bug, and would be difficult to implement. If you want it, you can make a pull request.
