### ISSUE TITLE
Drip particles from Small/Large eyeball blocks do nothing.

### ISSUE THREAD

**Issue by MagmaSlime123** [Rebirth-of-the-Night/BetterNether#9]
Add an option to allow eyeball blocks, like rain, to slowly fill cauldrons under them. If this won't be done, why have them drip at all.

**Comment by democat3457** [comment]
That sounds disgusting. Wanna use eye water to water your plants? Drink the tears of a nether eye?

**Comment by MagmaSlime123** [comment]
Well, it could be used for something at least...
Remove the effect altogether then

**Comment by Foreck1** [comment]
Just like water and lava particles can pass through blocks for aesthetic reasons, eyes can drop particles. Not everything has to copy 1.17 dripstone mechanics, particles are 99% cosmetic most of the time.

**Comment by TwilightFlower** [comment]
Yes, please let a visual effect be just a visual effect.
